// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://strostafzewfkycctzes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0cm9zdGFmemV3Zmt5Y2N0emVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDQ5MDIsImV4cCI6MjA2ODI4MDkwMn0.-0oG1dB4RvibQXOEFitA3D4-zs4s8vpojRZgHM1Z7Ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});